[server]
host = "192.168.1.9"
port = 54321
port_stat = 54320

[motor]
m1_mul = 1.0
m2_mul = 1.0
m3_mul = 1.0
m4_mul = 1.0
midpoint_angle = 90.0

[controller]
kp_x = 1.0  #forward backwards
kp_y = 1.2  #left right
kp_z = 20.0 #up down
kd_x = 0.1  #forward backwards
kd_y = 0.8  #left right
kd_z = 0.1  #up down
